// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_CcOTgeiRhZJh-gZcbSBHw_e_7dZBhoo',
    appId: '1:654643531072:web:8d2e698fd169722dbffea5',
    messagingSenderId: '654643531072',
    projectId: 'icecream-driver',
    authDomain: 'icecream-driver.firebaseapp.com',
    storageBucket: 'icecream-driver.appspot.com',
    measurementId: 'G-WN6VY6WEQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yctgv0vf3Y85KhKglGXLTQjVGzYLVoo',
    appId: '1:654643531072:android:05badd3eac8ef377bffea5',
    messagingSenderId: '654643531072',
    projectId: 'icecream-driver',
    storageBucket: 'icecream-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ho5Pvf0VdZvaFQK7kEPZM8de8ORHwA8',
    appId: '1:654643531072:ios:236f40c321a7e721bffea5',
    messagingSenderId: '654643531072',
    projectId: 'icecream-driver',
    storageBucket: 'icecream-driver.appspot.com',
    iosClientId:
        '654643531072-f42qkqv80ib6m13k0a3heqnhtlrc7bre.apps.googleusercontent.com',
    iosBundleId: 'com.example.icecream.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ho5Pvf0VdZvaFQK7kEPZM8de8ORHwA8',
    appId: '1:654643531072:ios:69f6dc96234adb71bffea5',
    messagingSenderId: '654643531072',
    projectId: 'icecream-driver',
    storageBucket: 'icecream-driver.appspot.com',
    iosClientId:
        '654643531072-ns7ringsc7bm56s0555fs2rsnuee603b.apps.googleusercontent.com',
    iosBundleId: 'com.example.icecream',
  );
}
